# Generated by Django 3.2.10 on 2021-12-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='total_student_count',
            field=models.IntegerField(default=0),
        ),
    ]
